# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

platform :ios, '10.0'

target 'PrecompiledExample' do
  pod 'SBTUITestTunnel/Server', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git'
end

target 'PrecompiledExampleUITests' do
  pod 'SBTUITestTunnel/Client', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git'
end

pre_install do |installer|
  raise "\n🚨  Do not launch 'pod install' manually, use `pod_builder` instead!\n" if !File.exist?('pod_builder.lock')
end
